flowchart TD;
    A([Start]) --> B["Initialize Variables"];
    B --> C["Display Main Menu"];
    C --> |User Input| D{Choice};
    D --> |1| E["Add Employee"];
    E --> F["Allocate Memory"];
    F --> G["Enter Employee Data"];
    G --> |1| H["Manager Data"];
    H --> I["Enter Weekly Salary"];
    I --> JJ["employees[numEmployees].salary = weeklySalary"];
    JJ --> J["Update Manager Stats"];
    J --> K["More Employees?"];
    K --> |Yes| F;
    K --> |No| C;
    G --> |2| L["Hourly Worker Data"];
    L --> M["Enter Hourly Rate"];
    M --> N["Enter Hours Worked"];
    N --> OO["employees[numEmployees].salary = CalculateHourlySalary(hourlyRate, hoursWorked)"];
    OO --> P["Update Hourly Worker Stats"];
    P --> K;
    G --> |3| Q["Commission Worker Data"];
    Q --> R["Enter Gross Weekly Sales"];
    R --> SS["employees[numEmployees].salary = CalculateCommissionSalary(grossSales)"];
    SS --> T["Update Commission Worker Stats"];
    T --> K;
    G --> |4| U["Pieceworker Data"];
    U --> V["Enter Wage per Item"];
    V --> W["Enter Items Produced"];
    W --> WW["employees[numEmployees].salary = CalculatePieceworkerSalary(wagePerItem, itemsProduced)"];
    WW --> Y["Update Pieceworker Stats"];
    Y --> K;
    D --> |2| Z["Find Specific Record"];
    Z --> AA["Enter Name to Search"];
    AA --> BB["Search for Employee"];
    BB --> CC["Display Employee Info"];
    CC --> C;
    D --> |3| DD["Summary Report"];
    DD --> EE["Calculate and Display Summary"];
    EE --> C;
    D --> |4| FF["Quit"];
    FF --> GG["Display Employee Info"];
    GG --> HH["Memory Deallocation"];
    HH --> II([End]);
