flowchart TD;
    A([Start])-->B["
    intializations 

    total_numbers = 100,
    count = 1,
    logged_in_user = -1,
    system_constant = 1001


    manager_password = 123,
    manager_account = 1001000,
    float manager_balance = 1.5
    
    new_balance = -1;

    check_user = true,
    terminate=false
    
    "];


    B-->C["
    
    intialising the account and balace array

    account[total_numbers][2] = {
        {manager_account,manager_password},
    }
    balance[total_numbers] = {{manager_balance}}

    "];


    C-->D{terminate = false};

    D -->|True| E[/read transaction/];

    D -->|False| E1([End]);

    E -->F["
        transaction = toupper(transaction)
        login_pin = 0
    "];

    F --> G{transaction = 'O'};

    G --> |True| H{cout < total_numbers};

    H --> |True| I{logged_in_user >= 0};

    H --> |False| I1[/ print 'The maximum number of accounts has been reached. You can't create a new account now.' /];

    I1 --> D;

    I --> |True| J[/print 'to create an account you've to log out'/];

    J --> D;

    I --> |False| J1{login_pin < 100 or login_pin >= 1000 or new_balance <= 10};

    J1 --> |True| J2[/print 'Choose a 3 digit pin code that starts without 0 for your account' /];

    J1 --> |False| K["new_acc = manager_account + count"];
    
    K --> L[/print 'Your account is created successfully! Your account number is new_acc'/];

    L --> L1["
    account[count][0] = new_acc
    account[count][1] = login_pin
    balance[count] = new_balance
    logged_in_user = count
    count = count + 1
    "];

    L1 --> D;

    J2 --> J3[/read login_pin/];

    J3 --> J4[/print 'Deposit money --minimum amount - $10 : $' /];

    J4 --> J5[/read new_balance/];

    J5 --> J1;

    G --> |False| M{logged_in_user < 0};


    M --> |True| N[/print 'You are not logged in Enter your account number : + system_constant'/]

    N --> O[/read login_acc/]

    O --> P{account--login_acc--0-- = 0}

    P --> |True| P1[/print 'No account found please try again!'/]

    P1 --> D

    M --> |False| N1["login_acc = account[logged_in_user][0] - manager_account Your account number: account[logged_in_user][0]"]

    N1 --> N2[/read login_pin/]

    P --> |False| N2

    N2 --> N4["my_acc = manager_account + login_acc"]

    N4 --> Q{account'login_acc''0' == my_acc and account'login_acc''1' == login_pin}

    Q --> |True| Q1["logged_in_user = login_acc"]

    Q --> |False| Q2[/print 'Invalid Pin Code, Login denied!'/]

    Q2 --> D

    Q1 --> R{logged_in_user >= 0}

    R --> |False| R1[/print 'Login first to access this page!'/]

    R1 --> D

    
    R  -->|True| R5[/print Your account number is : account-logged_in_user--0-/]

    R5 --> S{transaction='B'}

    S --> |True| T[/Your balance is: $ balance-logged_in_user-/]

    T --> |Break| T1

    S --> |False| S1{transaction = 'D'}

    S1 --> |True| T2[/ Your current balance is: $balance-logged_in_user-/]

    T2 --> T3[/read new_balance/]

    T3 --> T4["balance[logged_in_user] += new_balance"]

    T4 --> |Break| T1

    S1 --> |False| S2{transaction = 'W'}

    S2 --> |True| T5[/read new_balance/]

    T5 --> T6["balance[logged_in_user] -= new_balance"]

    T6 --> |Break| T1

    S2 --> |False| S3{transaction = 'C'}

    S3 --> |True| T7[logged_in_user = -1]

    T7 --> |Break| T1

    S3 --> |False| S4{transaction = 'S'}

    S4 --> |True| U{logged_in_user = 0}

    U --> |False| U1[You have no permission to access this transaction]

    U1  --> |Break| T1

    U --> |True| U2{terminate = false}

    U2 --> |False| U3[terminate = false]

    U3 --> T1

    U2 --> |True| U4[/read transaction/]

    U4 --> V["tolower(transaction)"]

    V --> V1{transaction = 'i'}

    V1 --> |True|V5[/read interest/]

    V5 --> V6[i=0]

    V6 --> V7{i <= total_numbers-1}

    V7 --> |True|V71["temp = balance[i], temp *= (interest/100), balance[i] += temp"]

    V71 --> V72[i + 1]

    V72 --> V7

    V7 --> |False| V4[continue]


    V1 --> |False| V2{transaction = 'p'}

    V2 --> |True|V21[i=0]

    V21 --> V22{i <= total_numbers-1}

    V22 --> |True| V23{"account[i][0] != 0"}

    V23 --> |True| V24[/print account-i--0-  and $ balance-i-/]

    V24 --> V25[i + 1]

    V23 --> |False| V25

    V25 --> V22

    V22 --> |False| V4[continue]


    V2 --> |False| V3{transaction = 'e'}

    V3 --> |True| V31["terminate = true"]

    V31 --> |Break| V4

    V3 --> |False| V4

    V4 --> U2

    S4 --> |False| S5[Invalid transaction entered please choose one from the menu.]

    S5 -->T1

    T1[continue] --> D
